# Generated by Django 6.0 on 2026-01-05 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eventinvite",
            constraint=models.UniqueConstraint(
                fields=("user", "event"), name="unique_user_event_invite"
            ),
        ),
    ]
